services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    environment:
      - DATABASE_URL=sqlite:///./quiz_platform.db
    command: uvicorn main:app --host 0.0.0.1 --port 8000 --reload

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env
    environment:
      - VITE_API_URL=http://localhost:8000/api
    command: npm run dev -- --host
